// Generated by scripts/generate-build-info.ts — do not edit by hand
export const APP_VERSION = "0.0.2";
export const APP_BUILD_ID = "6ca0ff2";
export const APP_BUILT_AT = "2026-03-24T19:21:47.888Z";
