/**
 * Writes src/bun/build-info.generated.ts with git commit + timestamp.
 * Run automatically before `electrobun build` (see package.json).
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { execSync } from "child_process";

const root = join(import.meta.dir, "..");
const pkg = JSON.parse(readFileSync(join(root, "package.json"), "utf-8")) as { version: string };

let gitSha = "unknown";
try {
	gitSha = execSync("git rev-parse --short HEAD", { cwd: root, encoding: "utf-8" }).trim();
} catch {
	// not a git checkout or git missing
}

const builtAt = new Date().toISOString();

const out = `// Generated by scripts/generate-build-info.ts — do not edit by hand
export const APP_VERSION = ${JSON.stringify(pkg.version)};
export const APP_BUILD_ID = ${JSON.stringify(gitSha)};
export const APP_BUILT_AT = ${JSON.stringify(builtAt)};
`;

const dest = join(root, "src/bun/build-info.generated.ts");
writeFileSync(dest, out);
console.log(`[build-info] ${pkg.version} · ${gitSha} · ${builtAt}`);
